services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=lucky
      - DB_PASSWORD=#Db@1234
      - DB_NAME=reporting_system
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "#Db@1234"
      MYSQL_DATABASE: reporting_system
      MYSQL_USER: lucky
      MYSQL_PASSWORD: "#Db@1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
